<?php

use app\core\Application;

class m0009_populate_siswaMapel_table
{
    public function up(): void
    {
        $db = Application::$app->db;
        $SQL = "
        INSERT INTO SiswaMapel (ID_Siswa, Nama_Guru, Nama_Mapel, Nilai, Deskripsi)
VALUES
('S001', 'John Smith', 'Membaca', 'B', 'Baik'),
('S002', 'John Smith', 'Membaca', 'C', 'Cukup'),
('S003', 'John Smith', 'Membaca', 'D', 'Kurang'),
('S004', 'John Smith', 'Membaca', 'D', 'Kurang'),
('S005', 'John Smith', 'Membaca', 'C', 'Cukup'),
('S006', 'John Smith', 'Membaca', 'C', 'Cukup'),
('S007', 'John Smith', 'Membaca', 'B', 'Baik'),
('S008', 'John Smith', 'Membaca', 'B', 'Baik'),
('S009', 'John Smith', 'Membaca', 'A', 'Sangat Baik'),
('S010', 'John Smith', 'Membaca', 'C', 'Cukup'),
('S011', 'Jane Doe', 'Menulis', 'B', 'Baik'),
('S012', 'Jane Doe', 'Menulis', 'B', 'Baik'),
('S013', 'Jane Doe', 'Menulis', 'A', 'Sangat Baik'),
('S014', 'Jane Doe', 'Menulis', 'D', 'Kurang'),
('S015', 'Jane Doe', 'Menulis', 'D', 'Kurang'),
('S016', 'Jane Doe', 'Menulis', 'D', 'Kurang'),
('S017', 'Jane Doe', 'Menulis', 'A', 'Sangat Baik'),
('S018', 'Jane Doe', 'Menulis', 'B', 'Baik'),
('S019', 'Jane Doe', 'Menulis', 'B', 'Baik'),
('S020', 'Jane Doe', 'Menulis', 'D', 'Kurang'),
('S021', 'Michael Johnson', 'Berhitung', 'B', 'Baik'),
('S022', 'Michael Johnson', 'Berhitung', 'D', 'Kurang'),
('S023', 'Michael Johnson', 'Berhitung', 'D', 'Kurang'),
('S024', 'Michael Johnson', 'Berhitung', 'D', 'Kurang'),
('S025', 'Michael Johnson', 'Berhitung', 'D', 'Kurang'),
('S026', 'Michael Johnson', 'Berhitung', 'B', 'Baik'),
('S027', 'Michael Johnson', 'Berhitung', 'B', 'Baik'),
('S028', 'Michael Johnson', 'Berhitung', 'C', 'Cukup'),
('S029', 'Michael Johnson', 'Berhitung', 'A', 'Sangat Baik'),
('S030', 'Michael Johnson', 'Berhitung', 'D', 'Kurang'),
('S031', 'Emily Brown', 'Menggambar', 'C', 'Cukup'),
('S032', 'Emily Brown', 'Menggambar', 'D', 'Kurang'),
('S033', 'Emily Brown', 'Menggambar', 'A', 'Sangat Baik'),
('S034', 'Emily Brown', 'Menggambar', 'C', 'Cukup'),
('S035', 'Emily Brown', 'Menggambar', 'A', 'Sangat Baik'),
('S036', 'Emily Brown', 'Menggambar', 'B', 'Baik'),
('S037', 'Emily Brown', 'Menggambar', 'A', 'Sangat Baik'),
('S038', 'Emily Brown', 'Menggambar', 'D', 'Kurang'),
('S039', 'Emily Brown', 'Menggambar', 'A', 'Sangat Baik'),
('S040', 'Emily Brown', 'Menggambar', 'D', 'Kurang'),
('S041', 'Joshua Davis', 'Mewarnai', 'D', 'Kurang'),
('S042', 'Joshua Davis', 'Mewarnai', 'B', 'Baik'),
('S043', 'Joshua Davis', 'Mewarnai', 'D', 'Kurang'),
('S044', 'Joshua Davis', 'Mewarnai', 'B', 'Baik'),
('S045', 'Joshua Davis', 'Mewarnai', 'D', 'Kurang'),
('S046', 'Joshua Davis', 'Mewarnai', 'B', 'Baik'),
('S047', 'Joshua Davis', 'Mewarnai', 'D', 'Kurang'),
('S048', 'Joshua Davis', 'Mewarnai', 'C', 'Cukup'),
('S049', 'Joshua Davis', 'Mewarnai', 'B', 'Baik'),
('S050', 'Joshua Davis', 'Mewarnai', 'D', 'Kurang'),
('S051', 'Ashley Miller', 'Menggambar', 'C', 'Cukup'),
('S052', 'Ashley Miller', 'Menggambar', 'B', 'Baik'),
('S053', 'Ashley Miller', 'Menggambar', 'A', 'Sangat Baik'),
('S054', 'Ashley Miller', 'Menggambar', 'D', 'Kurang'),
('S055', 'Ashley Miller', 'Menggambar', 'A', 'Sangat Baik'),
('S056', 'Ashley Miller', 'Menggambar', 'B', 'Baik'),
('S057', 'Ashley Miller', 'Menggambar', 'B', 'Baik'),
('S058', 'Ashley Miller', 'Menggambar', 'C', 'Cukup'),
('S059', 'Ashley Miller', 'Menggambar', 'B', 'Baik'),
('S060', 'Ashley Miller', 'Menggambar', 'D', 'Kurang'),
('S061', 'Matthew Wilson', 'Menulis', 'C', 'Cukup'),
('S062', 'Matthew Wilson', 'Menulis', 'D', 'Kurang'),
('S063', 'Matthew Wilson', 'Menulis', 'D', 'Kurang'),
('S064', 'Matthew Wilson', 'Menulis', 'C', 'Cukup'),
('S065', 'Matthew Wilson', 'Menulis', 'C', 'Cukup'),
('S066', 'Matthew Wilson', 'Menulis', 'C', 'Cukup'),
('S067', 'Matthew Wilson', 'Menulis', 'B', 'Baik'),
('S068', 'Matthew Wilson', 'Menulis', 'B', 'Baik'),
('S069', 'Matthew Wilson', 'Menulis', 'C', 'Cukup'),
('S070', 'Matthew Wilson', 'Menulis', 'D', 'Kurang'),
('S071', 'Olivia Moore', 'Berhitung', 'B', 'Baik'),
('S072', 'Olivia Moore', 'Berhitung', 'A', 'Sangat Baik'),
('S073', 'Olivia Moore', 'Berhitung', 'D', 'Kurang'),
('S074', 'Olivia Moore', 'Berhitung', 'A', 'Sangat Baik'),
('S075', 'Olivia Moore', 'Berhitung', 'D', 'Kurang'),
('S076', 'Olivia Moore', 'Berhitung', 'C', 'Cukup'),
('S077', 'Olivia Moore', 'Berhitung', 'D', 'Kurang'),
('S078', 'Olivia Moore', 'Berhitung', 'B', 'Baik'),
('S079', 'Olivia Moore', 'Berhitung', 'B', 'Baik'),
('S080', 'Olivia Moore', 'Berhitung', 'A', 'Sangat Baik'),
('S081', 'Jacob Taylor', 'Menggambar', 'D', 'Kurang'),
('S082', 'Jacob Taylor', 'Menggambar', 'B', 'Baik'),
('S083', 'Jacob Taylor', 'Menggambar', 'D', 'Kurang'),
('S084', 'Jacob Taylor', 'Menggambar', 'C', 'Cukup'),
('S085', 'Jacob Taylor', 'Menggambar', 'C', 'Cukup'),
('S086', 'Jacob Taylor', 'Menggambar', 'C', 'Cukup'),
('S087', 'Jacob Taylor', 'Menggambar', 'D', 'Kurang'),
('S088', 'Jacob Taylor', 'Menggambar', 'C', 'Cukup'),
('S089', 'Jacob Taylor', 'Menggambar', 'B', 'Baik'),
('S090', 'Jacob Taylor', 'Menggambar', 'D', 'Kurang'),
('S091', 'Isabella Anders', 'Mewarnai', 'D', 'Kurang'),
('S092', 'Isabella Anders', 'Mewarnai', 'B', 'Baik'),
('S093', 'Isabella Anders', 'Mewarnai', 'C', 'Cukup'),
('S094', 'Isabella Anders', 'Mewarnai', 'A', 'Sangat Baik'),
('S095', 'Isabella Anders', 'Mewarnai', 'B', 'Baik'),
('S096', 'Isabella Anders', 'Mewarnai', 'A', 'Sangat Baik'),
('S097', 'Isabella Anders', 'Mewarnai', 'C', 'Cukup'),
('S098', 'Isabella Anders', 'Mewarnai', 'A', 'Sangat Baik'),
('S099', 'Isabella Anders', 'Mewarnai', 'A', 'Sangat Baik'),
('S100', 'Isabella Anders', 'Mewarnai', 'B', 'Baik'),
('S001', 'Sudirman Sastra', 'Menulis', 'D', 'Kurang'),
('S002', 'Sudirman Sastra', 'Menulis', 'B', 'Baik'),
('S003', 'Sudirman Sastra', 'Menulis', 'D', 'Kurang'),
('S004', 'Sudirman Sastra', 'Menulis', 'C', 'Cukup'),
('S005', 'Sudirman Sastra', 'Menulis', 'B', 'Baik'),
('S006', 'Sudirman Sastra', 'Menulis', 'A', 'Sangat Baik'),
('S007', 'Sudirman Sastra', 'Menulis', 'D', 'Kurang'),
('S008', 'Sudirman Sastra', 'Menulis', 'A', 'Sangat Baik'),
('S009', 'Sudirman Sastra', 'Menulis', 'B', 'Baik'),
('S010', 'Sudirman Sastra', 'Menulis', 'B', 'Baik'),
('S011', 'Tuti Wulan', 'Berhitung', 'A', 'Sangat Baik'),
('S012', 'Tuti Wulan', 'Berhitung', 'C', 'Cukup'),
('S013', 'Tuti Wulan', 'Berhitung', 'B', 'Baik'),
('S014', 'Tuti Wulan', 'Berhitung', 'D', 'Kurang'),
('S015', 'Tuti Wulan', 'Berhitung', 'B', 'Baik'),
('S016', 'Tuti Wulan', 'Berhitung', 'A', 'Sangat Baik'),
('S017', 'Tuti Wulan', 'Berhitung', 'C', 'Cukup'),
('S018', 'Tuti Wulan', 'Berhitung', 'B', 'Baik'),
('S019', 'Tuti Wulan', 'Berhitung', 'D', 'Kurang'),
('S020', 'Tuti Wulan', 'Berhitung', 'A', 'Sangat Baik'),
('S021', 'Agus Gunawan', 'Menggambar', 'C', 'Cukup'),
('S022', 'Agus Gunawan', 'Menggambar', 'B', 'Baik'),
('S023', 'Agus Gunawan', 'Menggambar', 'D', 'Kurang'),
('S024', 'Agus Gunawan', 'Menggambar', 'A', 'Sangat Baik'),
('S025', 'Agus Gunawan', 'Menggambar', 'C', 'Cukup'),
('S026', 'Agus Gunawan', 'Menggambar', 'C', 'Cukup'),
('S027', 'Agus Gunawan', 'Menggambar', 'B', 'Baik'),
('S028', 'Agus Gunawan', 'Menggambar', 'B', 'Baik'),
('S029', 'Agus Gunawan', 'Menggambar', 'D', 'Kurang'),
('S030', 'Agus Gunawan', 'Menggambar', 'B', 'Baik'),
('S031', 'Rina Purnama', 'Mewarnai', 'C', 'Cukup'),
('S032', 'Rina Purnama', 'Mewarnai', 'B', 'Baik'),
('S033', 'Rina Purnama', 'Mewarnai', 'C', 'Cukup'),
('S034', 'Rina Purnama', 'Mewarnai', 'D', 'Kurang'),
('S035', 'Rina Purnama', 'Mewarnai', 'D', 'Kurang'),
('S036', 'Rina Purnama', 'Mewarnai', 'A', 'Sangat Baik'),
('S037', 'Rina Purnama', 'Mewarnai', 'A', 'Sangat Baik'),
('S038', 'Rina Purnama', 'Mewarnai', 'C', 'Cukup'),
('S039', 'Rina Purnama', 'Mewarnai', 'A', 'Sangat Baik'),
('S040', 'Rina Purnama', 'Mewarnai', 'D', 'Kurang'),
('S041', 'Budi Hartono', 'Menggambar', 'B', 'Baik'),
('S042', 'Budi Hartono', 'Menggambar', 'B', 'Baik'),
('S043', 'Budi Hartono', 'Menggambar', 'B', 'Baik'),
('S044', 'Budi Hartono', 'Menggambar', 'C', 'Cukup'),
('S045', 'Budi Hartono', 'Menggambar', 'A', 'Sangat Baik'),
('S046', 'Budi Hartono', 'Menggambar', 'D', 'Kurang'),
('S047', 'Budi Hartono', 'Menggambar', 'B', 'Baik'),
('S048', 'Budi Hartono', 'Menggambar', 'A', 'Sangat Baik'),
('S049', 'Budi Hartono', 'Menggambar', 'D', 'Kurang'),
('S050', 'Budi Hartono', 'Menggambar', 'D', 'Kurang'),
('S051', 'Diana Sari', 'Menulis', 'B', 'Baik'),
('S052', 'Diana Sari', 'Menulis', 'D', 'Kurang'),
('S053', 'Diana Sari', 'Menulis', 'B', 'Baik'),
('S054', 'Diana Sari', 'Menulis', 'B', 'Baik'),
('S055', 'Diana Sari', 'Menulis', 'B', 'Baik'),
('S056', 'Diana Sari', 'Menulis', 'C', 'Cukup'),
('S057', 'Diana Sari', 'Menulis', 'A', 'Sangat Baik'),
('S058', 'Diana Sari', 'Menulis', 'D', 'Kurang'),
('S059', 'Diana Sari', 'Menulis', 'D', 'Kurang'),
('S060', 'Diana Sari', 'Menulis', 'A', 'Sangat Baik'),
('S061', 'Eko Prasetyo', 'Berhitung', 'B', 'Baik'),
('S062', 'Eko Prasetyo', 'Berhitung', 'A', 'Sangat Baik'),
('S063', 'Eko Prasetyo', 'Berhitung', 'B', 'Baik'),
('S064', 'Eko Prasetyo', 'Berhitung', 'D', 'Kurang'),
('S065', 'Eko Prasetyo', 'Berhitung', 'B', 'Baik'),
('S066', 'Eko Prasetyo', 'Berhitung', 'C', 'Cukup'),
('S067', 'Eko Prasetyo', 'Berhitung', 'A', 'Sangat Baik'),
('S068', 'Eko Prasetyo', 'Berhitung', 'C', 'Cukup'),
('S069', 'Eko Prasetyo', 'Berhitung', 'D', 'Kurang'),
('S070', 'Eko Prasetyo', 'Berhitung', 'D', 'Kurang'),
('S071', 'Fajar Wahyudi', 'Menggambar', 'B', 'Baik'),
('S072', 'Fajar Wahyudi', 'Menggambar', 'D', 'Kurang'),
('S073', 'Fajar Wahyudi', 'Menggambar', 'B', 'Baik'),
('S074', 'Fajar Wahyudi', 'Menggambar', 'D', 'Kurang'),
('S075', 'Fajar Wahyudi', 'Menggambar', 'A', 'Sangat Baik'),
('S076', 'Fajar Wahyudi', 'Menggambar', 'C', 'Cukup'),
('S077', 'Fajar Wahyudi', 'Menggambar', 'B', 'Baik'),
('S078', 'Fajar Wahyudi', 'Menggambar', 'A', 'Sangat Baik'),
('S079', 'Fajar Wahyudi', 'Menggambar', 'A', 'Sangat Baik'),
('S080', 'Fajar Wahyudi', 'Menggambar', 'C', 'Cukup'),
('S081', 'Gusti Ayu', 'Mewarnai', 'C', 'Cukup'),
('S082', 'Gusti Ayu', 'Mewarnai', 'C', 'Cukup'),
('S083', 'Gusti Ayu', 'Mewarnai', 'C', 'Cukup'),
('S084', 'Gusti Ayu', 'Mewarnai', 'A', 'Sangat Baik'),
('S085', 'Gusti Ayu', 'Mewarnai', 'C', 'Cukup'),
('S086', 'Gusti Ayu', 'Mewarnai', 'D', 'Kurang'),
('S087', 'Gusti Ayu', 'Mewarnai', 'B', 'Baik'),
('S088', 'Gusti Ayu', 'Mewarnai', 'C', 'Cukup'),
('S089', 'Gusti Ayu', 'Mewarnai', 'A', 'Sangat Baik'),
('S090', 'Gusti Ayu', 'Mewarnai', 'D', 'Kurang'),
('S091', 'Hendra Setiawan', 'Menggambar', 'C', 'Cukup'),
('S092', 'Hendra Setiawan', 'Menggambar', 'D', 'Kurang'),
('S093', 'Hendra Setiawan', 'Menggambar', 'D', 'Kurang'),
('S094', 'Hendra Setiawan', 'Menggambar', 'D', 'Kurang'),
('S095', 'Hendra Setiawan', 'Menggambar', 'D', 'Kurang'),
('S096', 'Hendra Setiawan', 'Menggambar', 'D', 'Kurang'),
('S097', 'Hendra Setiawan', 'Menggambar', 'B', 'Baik'),
('S098', 'Hendra Setiawan', 'Menggambar', 'A', 'Sangat Baik'),
('S099', 'Hendra Setiawan', 'Menggambar', 'C', 'Cukup'),
('S100', 'Hendra Setiawan', 'Menggambar', 'A', 'Sangat Baik'),
('S001', 'Olivia Moore', 'Berhitung', 'B', 'Baik'),
('S002', 'Olivia Moore', 'Berhitung', 'A', 'Sangat Baik'),
('S003', 'Olivia Moore', 'Berhitung', 'C', 'Cukup'),
('S004', 'Olivia Moore', 'Berhitung', 'D', 'Kurang'),
('S005', 'Olivia Moore', 'Berhitung', 'D', 'Kurang'),
('S006', 'Olivia Moore', 'Berhitung', 'D', 'Kurang'),
('S007', 'Olivia Moore', 'Berhitung', 'C', 'Cukup'),
('S008', 'Olivia Moore', 'Berhitung', 'D', 'Kurang'),
('S009', 'Olivia Moore', 'Berhitung', 'A', 'Sangat Baik'),
('S010', 'Olivia Moore', 'Berhitung', 'D', 'Kurang'),
('S011', 'Joshua Davis', 'Menggambar', 'D', 'Kurang'),
('S012', 'Joshua Davis', 'Menggambar', 'C', 'Cukup'),
('S013', 'Joshua Davis', 'Menggambar', 'C', 'Cukup'),
('S014', 'Joshua Davis', 'Menggambar', 'D', 'Kurang'),
('S015', 'Joshua Davis', 'Menggambar', 'A', 'Sangat Baik'),
('S016', 'Joshua Davis', 'Menggambar', 'D', 'Kurang'),
('S017', 'Joshua Davis', 'Menggambar', 'B', 'Baik'),
('S018', 'Joshua Davis', 'Menggambar', 'D', 'Kurang'),
('S019', 'Joshua Davis', 'Menggambar', 'B', 'Baik'),
('S020', 'Joshua Davis', 'Menggambar', 'B', 'Baik'),
('S021', 'Jane Doe', 'Mewarnai', 'D', 'Kurang'),
('S022', 'Jane Doe', 'Mewarnai', 'B', 'Baik'),
('S023', 'Jane Doe', 'Mewarnai', 'B', 'Baik'),
('S024', 'Jane Doe', 'Mewarnai', 'C', 'Cukup'),
('S025', 'Jane Doe', 'Mewarnai', 'A', 'Sangat Baik'),
('S026', 'Jane Doe', 'Mewarnai', 'A', 'Sangat Baik'),
('S027', 'Jane Doe', 'Mewarnai', 'B', 'Baik'),
('S028', 'Jane Doe', 'Mewarnai', 'D', 'Kurang'),
('S029', 'Jane Doe', 'Mewarnai', 'D', 'Kurang'),
('S030', 'Jane Doe', 'Mewarnai', 'A', 'Sangat Baik'),
('S031', 'Diana Sari', 'Menggambar', 'C', 'Cukup'),
('S032', 'Diana Sari', 'Menggambar', 'D', 'Kurang'),
('S033', 'Diana Sari', 'Menggambar', 'C', 'Cukup'),
('S034', 'Diana Sari', 'Menggambar', 'C', 'Cukup'),
('S035', 'Diana Sari', 'Menggambar', 'A', 'Sangat Baik'),
('S036', 'Diana Sari', 'Menggambar', 'A', 'Sangat Baik'),
('S037', 'Diana Sari', 'Menggambar', 'D', 'Kurang'),
('S038', 'Diana Sari', 'Menggambar', 'B', 'Baik'),
('S039', 'Diana Sari', 'Menggambar', 'C', 'Cukup'),
('S040', 'Diana Sari', 'Menggambar', 'C', 'Cukup'),
('S041', 'Fajar Wahyudi', 'Menulis', 'D', 'Kurang'),
('S042', 'Fajar Wahyudi', 'Menulis', 'A', 'Sangat Baik'),
('S043', 'Fajar Wahyudi', 'Menulis', 'B', 'Baik'),
('S044', 'Fajar Wahyudi', 'Menulis', 'C', 'Cukup'),
('S045', 'Fajar Wahyudi', 'Menulis', 'B', 'Baik'),
('S046', 'Fajar Wahyudi', 'Menulis', 'C', 'Cukup'),
('S047', 'Fajar Wahyudi', 'Menulis', 'B', 'Baik'),
('S048', 'Fajar Wahyudi', 'Menulis', 'C', 'Cukup'),
('S049', 'Fajar Wahyudi', 'Menulis', 'B', 'Baik'),
('S050', 'Fajar Wahyudi', 'Menulis', 'A', 'Sangat Baik'),
('S051', 'Gusti Ayu', 'Berhitung', 'B', 'Baik'),
('S052', 'Gusti Ayu', 'Berhitung', 'C', 'Cukup'),
('S053', 'Gusti Ayu', 'Berhitung', 'D', 'Kurang'),
('S054', 'Gusti Ayu', 'Berhitung', 'A', 'Sangat Baik'),
('S055', 'Gusti Ayu', 'Berhitung', 'C', 'Cukup'),
('S056', 'Gusti Ayu', 'Berhitung', 'B', 'Baik'),
('S057', 'Gusti Ayu', 'Berhitung', 'B', 'Baik'),
('S058', 'Gusti Ayu', 'Berhitung', 'A', 'Sangat Baik'),
('S059', 'Gusti Ayu', 'Berhitung', 'A', 'Sangat Baik'),
('S060', 'Gusti Ayu', 'Berhitung', 'C', 'Cukup'),
('S061', 'Rina Purnama', 'Menggambar', 'B', 'Baik'),
('S062', 'Rina Purnama', 'Menggambar', 'D', 'Kurang'),
('S063', 'Rina Purnama', 'Menggambar', 'B', 'Baik'),
('S064', 'Rina Purnama', 'Menggambar', 'A', 'Sangat Baik'),
('S065', 'Rina Purnama', 'Menggambar', 'C', 'Cukup'),
('S066', 'Rina Purnama', 'Menggambar', 'B', 'Baik'),
('S067', 'Rina Purnama', 'Menggambar', 'A', 'Sangat Baik'),
('S068', 'Rina Purnama', 'Menggambar', 'A', 'Sangat Baik'),
('S069', 'Rina Purnama', 'Menggambar', 'B', 'Baik'),
('S070', 'Rina Purnama', 'Menggambar', 'B', 'Baik'),
('S071', 'Ashley Miller', 'Mewarnai', 'D', 'Kurang'),
('S072', 'Ashley Miller', 'Mewarnai', 'D', 'Kurang'),
('S073', 'Ashley Miller', 'Mewarnai', 'B', 'Baik'),
('S074', 'Ashley Miller', 'Mewarnai', 'A', 'Sangat Baik'),
('S075', 'Ashley Miller', 'Mewarnai', 'D', 'Kurang'),
('S076', 'Ashley Miller', 'Mewarnai', 'D', 'Kurang'),
('S077', 'Ashley Miller', 'Mewarnai', 'B', 'Baik'),
('S078', 'Ashley Miller', 'Mewarnai', 'C', 'Cukup'),
('S079', 'Ashley Miller', 'Mewarnai', 'D', 'Kurang'),
('S080', 'Ashley Miller', 'Mewarnai', 'B', 'Baik'),
('S081', 'Isabella Anders', 'Menggambar', 'A', 'Sangat Baik'),
('S082', 'Isabella Anders', 'Menggambar', 'D', 'Kurang'),
('S083', 'Isabella Anders', 'Menggambar', 'A', 'Sangat Baik'),
('S084', 'Isabella Anders', 'Menggambar', 'A', 'Sangat Baik'),
('S085', 'Isabella Anders', 'Menggambar', 'D', 'Kurang'),
('S086', 'Isabella Anders', 'Menggambar', 'C', 'Cukup'),
('S087', 'Isabella Anders', 'Menggambar', 'D', 'Kurang'),
('S088', 'Isabella Anders', 'Menggambar', 'A', 'Sangat Baik'),
('S089', 'Isabella Anders', 'Menggambar', 'B', 'Baik'),
('S090', 'Isabella Anders', 'Menggambar', 'D', 'Kurang'),
('S091', 'Sudirman Sastra', 'Menulis', 'D', 'Kurang'),
('S092', 'Sudirman Sastra', 'Menulis', 'C', 'Cukup'),
('S093', 'Sudirman Sastra', 'Menulis', 'B', 'Baik'),
('S094', 'Sudirman Sastra', 'Menulis', 'A', 'Sangat Baik'),
('S095', 'Sudirman Sastra', 'Menulis', 'D', 'Kurang'),
('S096', 'Sudirman Sastra', 'Menulis', 'A', 'Sangat Baik'),
('S097', 'Sudirman Sastra', 'Menulis', 'D', 'Kurang'),
('S098', 'Sudirman Sastra', 'Menulis', 'D', 'Kurang'),
('S099', 'Sudirman Sastra', 'Menulis', 'D', 'Kurang'),
('S100', 'Sudirman Sastra', 'Menulis', 'A', 'Sangat Baik');




        ";
        $db->pdo->exec($SQL);
    }

    public function down(): void
    {
        $db = Application::$app->db;
        $SQL = "DROP TABLE Siswa();";
        $db->pdo->exec($SQL);
    }
}

?>

