<?php

use app\core\Application;

class m0023_populate_transaksi_table
{
    public function up(): void
    {
        $db = Application::$app->db;
        $SQL = "
        
            INSERT INTO Transaksi (Date, ID_Siswa, ID_Makanan, Deskripsi_Transaksi, Catatan_Guru)
VALUES
('2023-01-01', 'S001', 'M005', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa aktif dalam kegiatan memasak.'),
('2023-01-01', 'S002', 'M003', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-01', 'S003', 'M008', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-01', 'S004', 'M008', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-01', 'S005', 'M004', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-01', 'S006', 'M005', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menunjukkan kemampuan dalam mengikuti instruksi.'),
('2023-01-01', 'S007', 'M001', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-01', 'S008', 'M010', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa mulai bisa memahami konsep segitiga dan lingkaran.'),
('2023-01-01', 'S009', 'M007', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-01', 'S010', 'M009', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-01', 'S011', 'M005', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa mulai bisa memahami konsep segitiga dan lingkaran.'),
('2023-01-01', 'S012', 'M010', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa aktif dalam kegiatan memasak.'),
('2023-01-01', 'S013', 'M001', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa memahami konsep kiri dan kanan.'),
('2023-01-01', 'S014', 'M004', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-01', 'S015', 'M001', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-01', 'S016', 'M008', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-01', 'S017', 'M003', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-01', 'S018', 'M001', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-01', 'S019', 'M008', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-01', 'S020', 'M002', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bahan.'),
('2023-01-01', 'S021', 'M006', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-01', 'S022', 'M002', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa memahami konsep kiri dan kanan.'),
('2023-01-01', 'S023', 'M004', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-01', 'S024', 'M005', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.'),
('2023-01-01', 'S025', 'M006', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-01', 'S026', 'M004', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-01', 'S027', 'M004', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-01', 'S028', 'M009', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-01', 'S029', 'M005', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa memahami konsep kiri dan kanan.'),
('2023-01-01', 'S030', 'M009', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-01', 'S031', 'M010', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa aktif dalam kegiatan membentuk pola.'),
('2023-01-01', 'S032', 'M002', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-01', 'S033', 'M006', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-01', 'S034', 'M001', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-01', 'S035', 'M006', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-01', 'S036', 'M007', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-01', 'S037', 'M008', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-01', 'S038', 'M001', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa menunjukkan kemampuan dalam mengikuti instruksi.'),
('2023-01-01', 'S039', 'M005', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-01', 'S040', 'M008', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-01', 'S041', 'M009', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-01', 'S042', 'M003', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-01', 'S043', 'M001', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-01', 'S044', 'M005', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa mulai bisa memahami konsep segitiga dan lingkaran.'),
('2023-01-01', 'S045', 'M001', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-01', 'S046', 'M005', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bahan.'),
('2023-01-01', 'S047', 'M009', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa aktif dalam kegiatan memasak.'),
('2023-01-01', 'S048', 'M002', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal hewan.'),
('2023-01-01', 'S049', 'M008', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-01', 'S050', 'M004', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-01', 'S051', 'M004', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-01', 'S052', 'M009', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-01', 'S053', 'M005', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa memahami konsep kiri dan kanan.'),
('2023-01-01', 'S054', 'M009', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-01', 'S055', 'M004', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-01', 'S056', 'M006', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-01', 'S057', 'M002', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-01', 'S058', 'M005', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-01', 'S059', 'M005', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa aktif dalam kegiatan memasak.'),
('2023-01-01', 'S060', 'M004', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa aktif dalam kegiatan membentuk pola.'),
('2023-01-01', 'S061', 'M004', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-01', 'S062', 'M006', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-01', 'S063', 'M001', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menunjukkan minat yang tinggi dalam belajar.'),
('2023-01-01', 'S064', 'M002', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.'),
('2023-01-01', 'S065', 'M004', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-01', 'S066', 'M001', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa mulai bisa memahami konsep segitiga dan lingkaran.'),
('2023-01-01', 'S067', 'M009', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-01', 'S068', 'M001', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-01', 'S069', 'M005', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-01', 'S070', 'M007', 'belajar menulis huruf dan angka', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-01', 'S071', 'M006', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-01', 'S072', 'M001', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-01', 'S073', 'M002', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-01', 'S074', 'M004', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-01', 'S075', 'M001', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-01', 'S076', 'M006', 'belajar menulis huruf dan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-01', 'S077', 'M002', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-01', 'S078', 'M009', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-01', 'S079', 'M006', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-01', 'S080', 'M006', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bahan.'),
('2023-01-01', 'S081', 'M002', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa aktif dalam kegiatan membentuk pola.'),
('2023-01-01', 'S082', 'M006', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-01', 'S083', 'M009', 'belajar menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-01', 'S084', 'M003', 'belajar menulis huruf dan angka', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-01', 'S085', 'M002', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa mulai bisa memahami konsep segitiga dan lingkaran.'),
('2023-01-01', 'S086', 'M007', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-01', 'S087', 'M005', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-01', 'S088', 'M001', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa aktif dalam kegiatan memasak.'),
('2023-01-01', 'S089', 'M008', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-01', 'S090', 'M002', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-01', 'S091', 'M007', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal hewan.'),
('2023-01-01', 'S092', 'M009', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-01', 'S093', 'M005', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-01', 'S094', 'M009', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-01', 'S095', 'M007', 'belajar menulis huruf dan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-01', 'S096', 'M006', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-01', 'S097', 'M007', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan kemampuan dalam mengikuti instruksi.'),
('2023-01-01', 'S098', 'M008', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-01', 'S099', 'M003', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa menunjukkan minat yang tinggi dalam belajar.'),
('2023-01-01', 'S100', 'M005', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-02', 'S001', 'M002', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal hewan.'),
('2023-01-02', 'S002', 'M005', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-02', 'S003', 'M006', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-02', 'S004', 'M003', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-02', 'S005', 'M008', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bahan.'),
('2023-01-02', 'S006', 'M009', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-02', 'S007', 'M006', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-02', 'S008', 'M004', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan minat yang tinggi dalam belajar.'),
('2023-01-02', 'S009', 'M010', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S010', 'M004', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-02', 'S011', 'M004', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S012', 'M005', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-02', 'S013', 'M008', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-02', 'S014', 'M001', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-02', 'S015', 'M005', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-02', 'S016', 'M003', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-02', 'S017', 'M009', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal hewan.'),
('2023-01-02', 'S018', 'M007', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-02', 'S019', 'M007', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-02', 'S020', 'M008', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa mulai bisa memahami konsep segitiga dan lingkaran.'),
('2023-01-02', 'S021', 'M010', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-02', 'S022', 'M007', 'belajar menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-02', 'S023', 'M002', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-02', 'S024', 'M007', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S025', 'M005', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-02', 'S026', 'M007', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-02', 'S027', 'M002', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa memahami konsep depan dan belakang.'),
('2023-01-02', 'S028', 'M005', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa memahami konsep kiri dan kanan.'),
('2023-01-02', 'S029', 'M004', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bahan.'),
('2023-01-02', 'S030', 'M005', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-02', 'S031', 'M001', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-02', 'S032', 'M005', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-02', 'S033', 'M001', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S034', 'M003', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-02', 'S035', 'M007', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S036', 'M008', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa memahami konsep depan dan belakang.'),
('2023-01-02', 'S037', 'M009', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menunjukkan kemampuan dalam mengikuti instruksi.'),
('2023-01-02', 'S038', 'M005', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa memahami konsep depan dan belakang.'),
('2023-01-02', 'S039', 'M006', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-02', 'S040', 'M009', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-02', 'S041', 'M002', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-02', 'S042', 'M001', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S043', 'M008', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-02', 'S044', 'M008', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bahan.'),
('2023-01-02', 'S045', 'M007', 'belajar menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-02', 'S046', 'M001', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-02', 'S047', 'M004', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-02', 'S048', 'M003', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-02', 'S049', 'M008', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S050', 'M003', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-02', 'S051', 'M010', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa mulai bisa memahami konsep segitiga dan lingkaran.'),
('2023-01-02', 'S052', 'M003', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-02', 'S053', 'M005', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.'),
('2023-01-02', 'S054', 'M003', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-02', 'S055', 'M009', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S056', 'M003', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-02', 'S057', 'M006', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-02', 'S058', 'M009', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-02', 'S059', 'M005', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-02', 'S060', 'M003', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa memahami konsep depan dan belakang.'),
('2023-01-02', 'S061', 'M005', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa menunjukkan minat yang tinggi dalam belajar.'),
('2023-01-02', 'S062', 'M002', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-02', 'S063', 'M010', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-02', 'S064', 'M001', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-02', 'S065', 'M006', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-02', 'S066', 'M002', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-02', 'S067', 'M008', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-02', 'S068', 'M006', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-02', 'S069', 'M006', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal hewan.'),
('2023-01-02', 'S070', 'M001', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-02', 'S071', 'M006', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-02', 'S072', 'M002', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-02', 'S073', 'M010', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-02', 'S074', 'M003', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa aktif dalam kegiatan membentuk pola.'),
('2023-01-02', 'S075', 'M004', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-02', 'S076', 'M002', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-02', 'S077', 'M008', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-02', 'S078', 'M005', 'belajar menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S079', 'M006', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-02', 'S080', 'M009', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-02', 'S081', 'M008', 'belajar menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-02', 'S082', 'M001', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-02', 'S083', 'M002', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-02', 'S084', 'M006', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-02', 'S085', 'M005', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-02', 'S086', 'M010', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-02', 'S087', 'M001', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-02', 'S088', 'M008', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-02', 'S089', 'M008', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-02', 'S090', 'M010', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa memahami konsep depan dan belakang.'),
('2023-01-02', 'S091', 'M002', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-02', 'S092', 'M001', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-02', 'S093', 'M010', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa aktif dalam kegiatan memasak.'),
('2023-01-02', 'S094', 'M009', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-02', 'S095', 'M009', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal hewan.'),
('2023-01-02', 'S096', 'M005', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal hewan.'),
('2023-01-02', 'S097', 'M009', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-02', 'S098', 'M010', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-02', 'S099', 'M004', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-02', 'S100', 'M007', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa mulai bisa memahami konsep segitiga dan lingkaran.'),
('2023-01-03', 'S001', 'M004', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-03', 'S002', 'M009', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-03', 'S003', 'M008', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-03', 'S004', 'M003', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-03', 'S005', 'M004', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-03', 'S006', 'M002', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bahan.'),
('2023-01-03', 'S007', 'M005', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-03', 'S008', 'M001', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.'),
('2023-01-03', 'S009', 'M009', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-03', 'S010', 'M001', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-03', 'S011', 'M005', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-03', 'S012', 'M004', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-03', 'S013', 'M004', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-03', 'S014', 'M003', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-03', 'S015', 'M007', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-03', 'S016', 'M006', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa memahami konsep kiri dan kanan.'),
('2023-01-03', 'S017', 'M002', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.'),
('2023-01-03', 'S018', 'M005', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-03', 'S019', 'M005', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-03', 'S020', 'M001', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-03', 'S021', 'M007', 'belajar menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-03', 'S022', 'M010', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bahan.'),
('2023-01-03', 'S023', 'M009', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-03', 'S024', 'M005', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-03', 'S025', 'M004', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-03', 'S026', 'M003', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal bentuk.'),
('2023-01-03', 'S027', 'M002', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-03', 'S028', 'M005', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-03', 'S029', 'M006', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-03', 'S030', 'M006', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-03', 'S031', 'M008', 'Membaca buku cerita dengan gambar, memahami konsep besar dan kecil dengan benda, berlatih menulis huruf dan angka', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-03', 'S032', 'M007', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.'),
('2023-01-03', 'S033', 'M001', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-03', 'S034', 'M010', 'Belajar bahasa Inggris dengan dialog, kegiatan rekreasi, memahami konsep besar dan kecil dengan alat bantu', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-03', 'S035', 'M007', 'Belajar menulis huruf dan angka dengan alat bantu, memahami konsep kanan dan kiri dengan gambar, berlatih membaca buku cerita dengan suara', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-03', 'S036', 'M001', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-03', 'S037', 'M001', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-03', 'S038', 'M008', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-03', 'S039', 'M006', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-03', 'S040', 'M005', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-03', 'S041', 'M003', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa mulai bisa memahami konsep segi empat dan persegi panjang.'),
('2023-01-03', 'S042', 'M008', 'belajar menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-03', 'S043', 'M001', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa memahami konsep tengah dan pinggir.'),
('2023-01-03', 'S044', 'M009', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-03', 'S045', 'M001', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-03', 'S046', 'M006', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa berpartisipasi aktif dalam kegiatan memasak.'),
('2023-01-03', 'S047', 'M003', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-03', 'S048', 'M003', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa mulai bisa memahami konsep lingkaran dan persegi.'),
('2023-01-03', 'S049', 'M010', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menunjukkan minat yang tinggi dalam belajar.'),
('2023-01-03', 'S050', 'M010', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-03', 'S051', 'M005', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-03', 'S052', 'M001', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-03', 'S053', 'M001', 'belajar menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-03', 'S054', 'M010', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa memahami konsep kiri dan kanan.'),
('2023-01-03', 'S055', 'M007', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-03', 'S056', 'M005', 'belajar menulis huruf dan angka', 'Siswa menyebutkan nama buah-buahan dengan baik.'),
('2023-01-03', 'S057', 'M008', 'Berlatih membaca alfabet dengan gambar, menyanyikan lagu, memahami konsep tambah dan kurang dengan suara', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-03', 'S058', 'M007', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.'),
('2023-01-03', 'S059', 'M007', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-03', 'S060', 'M003', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-03', 'S061', 'M003', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-03', 'S062', 'M003', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa aktif dalam kegiatan memasak.'),
('2023-01-03', 'S063', 'M001', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa berpartisipasi aktif dalam kegiatan melukis.'),
('2023-01-03', 'S064', 'M009', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal suara binatang.'),
('2023-01-03', 'S065', 'M006', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.'),
('2023-01-03', 'S066', 'M010', 'belajar menulis huruf dan angka', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-03', 'S067', 'M004', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa aktif dalam kegiatan bermain lego.'),
('2023-01-03', 'S068', 'M003', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-03', 'S069', 'M010', 'Berlatih membaca alfabet dengan suara, menyanyikan lagu, memahami konsep tambah dan kurang dengan benda', 'Siswa menunjukkan kemampuan dalam mengikuti instruksi.'),
('2023-01-03', 'S070', 'M002', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa aktif dalam kegiatan membentuk pola.'),
('2023-01-03', 'S071', 'M009', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Indonesia.'),
('2023-01-03', 'S072', 'M009', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan minat yang tinggi dalam belajar.'),
('2023-01-03', 'S073', 'M007', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-03', 'S074', 'M006', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-03', 'S075', 'M006', 'Belajar bahasa Inggris dengan lagu dan cerita, kegiatan olahraga, memahami konsep kiri dan kanan', 'Siswa aktif dalam kegiatan menari dan berolahraga.'),
('2023-01-03', 'S076', 'M005', 'Belajar menulis nama dengan suara, memahami konsep atas dan bawah dengan suara, berlatih membaca buku cerita dengan alat bantu', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-03', 'S077', 'M002', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-03', 'S078', 'M007', 'Belajar bahasa Inggris, kegiatan rekreasi, memahami konsep kanan dan kiri', 'Siswa aktif dalam kegiatan membentuk pola.'),
('2023-01-03', 'S079', 'M008', 'belajar menulis huruf dan angka', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-03', 'S080', 'M010', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa memahami konsep besar dan kecil.'),
('2023-01-03', 'S081', 'M006', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-03', 'S082', 'M010', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menyebutkan nama binatang dengan baik.'),
('2023-01-03', 'S083', 'M003', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa aktif dalam kegiatan memasak.'),
('2023-01-03', 'S084', 'M005', 'Belajar memahami warna, membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan alat bantu', 'Siswa menunjukkan kemampuan dalam mengikuti instruksi.'),
('2023-01-03', 'S085', 'M007', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-03', 'S086', 'M005', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa berpartisipasi aktif dalam kegiatan berkebun.'),
('2023-01-03', 'S087', 'M005', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-03', 'S088', 'M006', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-03', 'S089', 'M005', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa menunjukkan minat yang tinggi dalam belajar.'),
('2023-01-03', 'S090', 'M007', 'Berlatih mengerjakan soal matematika, memahami konsep tambah dan kurang dengan angka', 'Siswa aktif dalam kegiatan membentuk pola.'),
('2023-01-03', 'S091', 'M008', 'Membaca buku cerita dengan suara, memahami konsep depan dan belakang dengan gambar, berlatih menulis huruf dan angka dengan suara', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal hewan.'),
('2023-01-03', 'S092', 'M001', 'Berlatih menulis nama dengan alat bantu, memahami konsep atas dan bawah dengan gambar, belajar membaca buku cerita dengan gambar', 'Siswa memahami konsep depan dan belakang.'),
('2023-01-03', 'S093', 'M006', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa menunjukkan kemampuan dalam berbicara sederhana dalam bahasa Inggris.'),
('2023-01-03', 'S094', 'M008', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-03', 'S095', 'M004', 'Membaca buku cerita, memahami konsep besar dan kecil, berlatih menulis huruf dan angka', 'Siswa memahami konsep depan dan belakang.'),
('2023-01-03', 'S096', 'M009', 'Belajar menulis nama, memahami konsep atas dan bawah, berlatih membaca buku cerita', 'Siswa menyebutkan warna dengan baik.'),
('2023-01-03', 'S097', 'M006', 'Berlatih mengerjakan soal matematika dengan gambar, memahami konsep kiri dan kanan dengan suara, belajar bahasa Inggris dengan dialog dan gambar', 'Siswa menyebutkan nama sayur-sayuran dengan baik.'),
('2023-01-03', 'S098', 'M006', 'Belajar membaca buku cerita, berlatih soal matematika, memahami konsep tambah dan kurang', 'Siswa menunjukkan kemampuan dalam mengikuti instruksi.'),
('2023-01-03', 'S099', 'M003', 'Siswa menunjukkan perkembangan positif dalam belajar mengenal angka.', 'Siswa memahami konsep atas dan bawah.'),
('2023-01-03', 'S100', 'M001', 'Berlatih membaca alfabet, menyanyikan lagu, memahami konsep depan dan belakang', 'Siswa mulai bisa membaca huruf huruf dasar dengan benar.');

                ";
        $db->pdo->exec($SQL);
    }

    public function down(): void
    {
        $db = Application::$app->db;
        $SQL = "DROP TABLE Transaksi();";
        $db->pdo->exec($SQL);
    }
}

?>


